/*!
 * froala_editor v1.2.6 (http://editor.froala.com)
 * License http://editor.froala.com/license
 * Copyright 2014-2015 Froala Labs
 */

/**
 * Vietnamese
 */

$.Editable.LANGS['vi'] = {
    translation: {
        "Bold": "Đậm",
        "Italic": "Nghiên",
        "Underline": "Gạch chân",
        "Strikethrough": "Gạch giữa",
        "Font Size": "Cỡ chữ",
        "Color": "Màu chữ",
        "Background": "Màu nền",
        "Text": "Chữ",
        "Format Block": "Format Block",
        "Normal": "Bình thường",
        "Paragraph": "Đoạn",
        "Code": "Mã",
        "Quote": "Quote",
        "Heading 1": "Heading 1",
        "Heading 2": "Heading 2",
        "Heading 3": "Heading 3",
        "Heading 4": "Heading 4",
        "Heading 5": "Heading 5",
        "Heading 6": "Heading 6",
        "Block Style": "Block Style",
        "Alignment": "Canh lề",
        "Align Left": "Canh trái",
        "Align Center": "Canh giữa",
        "Align Right": "Canh phải",
        "Justify": "Canh đều",
        "Numbered List": "Numbered List",
        "Bulleted List": "Bulleted List",
        "Indent Less": "Indent Less",
        "Indent More": "Indent More",
        "Select All": "Chọn tất cả",
        "Insert Link": "Chèn liên kết",
        "Insert Image": "Chèn hình",
        "Insert Video": "Chèn phim",
        "Undo": "Undo",
        "Redo": "Redo",
        "Show HTML": "Mã HTML",
        "Float Left": "Float Left",
        "Float None": "Float None",
        "Float Right": "Float Right",
        "Replace Image": "Thay hình",
        "Remove Image": "Bỏ hình",
        "Title": "Tiêu đề",
        "Drop image": "Drop image",
        "or click": "or click",
        "or": "hoặc",
        "Enter URL": "Nhập URL",
        "Please wait!": "Xin chờ!",
        "Are you sure? Image will be deleted.": "Bạn có chắc không? Hình ảnh sẽ bị xóa.",
        "UNLINK": "UNLINK",
        "Open in new tab": "Open in new tab",
        "Type something": "Type something",
        "Cancel": "Bỏ qua",
        "OK": "Đồng ý",
        "Manage images": "Hình ảnh trên Server",
        "Delete": "Xóa",
        "Font Family": "Chọn Font",
        "Insert Horizontal Line": "Đường kẻ ngang",
        "Table": "Bảng",
        "Insert table": "Chèn bảng",
        "Cell": "Ô",
        "Row": "Dòng",
        "Column": "Cột",
        "Delete table": "Xóa bảng",
        "Insert cell before": "Chèn ô phía trước",
        "Insert cell after": "Chèn ô phía sau",
        "Delete cell": "Xóa ô",
        "Merge cells": "Gộp ô",
        "Horizontal split": "Horizontal split",
        "Vertical split": "Vertical split",
        "Insert row above": "Chèn hàng phía trước",
        "Insert row below": "Chèn hàng phía sau",
        "Delete row": "Xóa dòng",
        "Insert column before": "Chèn cột phía trước",
        "Insert column after": "Chèn cột phía sau",
        "Delete column": "Xóa cột",
        "Uploading image": "Uploading image",
        "Upload File": "Upload File",
        "Drop File": "Drop File",
        "Clear formatting": "Xóa định dạng"
    },
    direction: "ltr"
};
